<?php
return [
    "head" => "Kebijakan Privasi",
    "capt" => "Kebijakan privasi pengumpulan data atau informasi di website " . env('APP_TITLE') . ".",
    "content" =>
        "<p>Selamat datang di " . env('APP_TITLE') . " (di sini disebut sebagai \"Website\", \"" . env('APP_TITLE') . "\", \"Kami\", \"Kita\", \"Milik Kami\" dan afiliasinya). Kebijakan Privasi ini dirancang untuk memberi tahu Anda tentang bagaimana kami mengumpulkan, menggunakan, mengungkapkan, mentransfer, dan memproses informasi pengidentifikasi pribadi yang kami kumpulkan di Website (di sini disebut \"Informasi Pribadi\"). Setiap kali Anda mengunjungi Website, Anda menyetujui pengumpulan, penggunaan, pengungkapan, dan pemrosesan Informasi Pribadi sesuai dengan Kebijakan Privasi ini. Khususnya, jika Anda berada di wilayah hukum di luar Indonesia, Anda menyetujui transfer Informasi Pribadi Anda ke server dan sistem komputer kami di mana pun di dunia, termasuk ke negara-negara yang mungkin tidak memberikan tingkat perlindungan data yang setara dengan undang-undang. di yurisdiksi rumah Anda. Jika Anda memberikan Informasi Pribadi apa pun yang berkaitan dengan orang lain yang Anda nyatakan di sini dan setuju bahwa Anda telah memperoleh persetujuan yang tepat dari orang tersebut untuk penggunaan, pengungkapan, dan pemrosesan Informasi Pribadi tersebut sebagaimana dijelaskan dalam Kebijakan Privasi ini.</p>
        <p>Website secara aktif mengumpulkan Informasi Pribadi dari Anda ketika Anda mendaftar ke Website, ketika Anda mengirim email kepada administrator Website, dan ketika Anda mengirimkan informasi apa pun ke Website. Jenis-jenis Informasi Pribadi yang dapat Anda berikan meliputi nama Anda, informasi kontak termasuk alamat email, ID pengguna, dan informasi lain yang Anda masukkan dalam komunikasi atau pengajuan apa pun. Kami dapat menggunakan Informasi Pribadi ini untuk mendaftarkan Anda ke Website, untuk menanggapi pertanyaan Anda atau masalah yang Anda ajukan kepada administrator Website, untuk mengirim kiriman Anda ke Website dan untuk memberikan informasi kepada orang lain mengenai penggunaan Anda terhadap Website. Kami juga dapat menggunakan Informasi Pribadi untuk memberi tahu Anda tentang produk dan layanan yang mungkin menarik bagi Anda. Jika Anda ingin berlangganan buletin kami, kami akan menggunakan nama dan alamat email Anda untuk mengirim buletin kepada Anda. Demi menghormati privasi Anda, kami memberi Anda cara untuk berhenti berlangganan. Jika Anda tidak lagi ingin menerima buletin dan komunikasi promosi kami, Anda dapat memilih untuk tidak menerimanya dengan mengikuti instruksi yang termasuk dalam setiap buletin atau komunikasi atau dengan mengirim email kepada kami di " . env('MAIL_USERNAME') . ".</p>
        <p>Website dapat secara pasif mengumpulkan jenis informasi tertentu yang mengungkapkan frekuensi kunjungan Anda ke Website, waktu dan tanggal kunjungan Anda, halaman yang Anda tinjau, orang-orang yang berinteraksi dengan Anda dan informasi lainnya. Informasi dikumpulkan secara pasif melalui berbagai cara. Kami menggunakan alamat Protokol Internet (IP) untuk mengelola Website. Kami menggunakan data navigasi, termasuk file log dan data transmisi, untuk mengidentifikasi informasi tentang browser Anda dan sistem operasi, periode waktu di mana Anda mengunjungi Website atau sebagian dari Website dan anggota Website lainnya dengan siapa Anda berkolaborasi. Kami juga menggunakan layanan pelacakan pihak ketiga yang menggunakan teknologi pelacakan untuk melacak informasi yang tidak dapat diidentifikasi secara pribadi tentang pengunjung ke Website kami secara keseluruhan. Informasi ini digunakan untuk mengelola Website, melaporkan metrik penggunaan, dan jika tidak mengoperasikan serta meningkatkan konten Website.</p>
        <p>Seperti banyak situs Internet, Website dapat menggunakan file teks kecil yang disebut \"cookie\" yang dikirim ke hard drive komputer Anda untuk menyimpan bit informasi yang terkait dengan penggunaan Anda terhadap Website. Cookie dapat menyimpan berbagai informasi, termasuk alamat IP, data navigasi, informasi server, waktu transfer data, preferensi pengguna, dan kata sandi yang diperlukan untuk mengakses Website. Bagian 'Bantuan' pada bilah alat pada sebagian besar browser akan memberi tahu Anda cara mencegah browser Anda dari menerima cookie baru, bagaimana agar browser Anda memberi tahu Anda ketika Anda menerima cookie baru, atau cara mengkonfigurasi browser Anda untuk menolak cookie sekaligus. Namun, jika Anda menonaktifkan cookie, Anda mungkin tidak dapat mengakses fungsi-fungsi atau fitur-fitur penting dari Website dan penggunaan Anda atas Website mungkin terbatas. Website menggabungkan informasi yang dikumpulkan secara pasif (seperti dijelaskan di atas) dengan Informasi Pribadi yang dikumpulkan secara aktif dan informasi dapat dicatat sebagai bagian dari profil Anda. Kami mencatat dan menggunakan informasi pribadi yang Anda berikan untuk memproses pesanan di Website dan menyediakan layanan pelanggan. Ini dapat mencakup nama, informasi alamat, informasi pengiriman dan informasi kontak yang Anda masukkan dalam keranjang belanja. Informasi ini digunakan bersamaan dengan pemrosesan, pengiriman, dan pemenuhan pesanan melalui Website.</p>
        <p>Kami dapat mengungkapkan Informasi Pribadi kepada penyedia layanan pihak ketiga yang melakukan layanan atas nama kami, termasuk mereka yang meng-hosting server kami dan menyediakan layanan dukungan teknis lainnya. Kami menggunakan pihak ketiga seperti pemroses pembayaran untuk menagih Anda untuk produk dan perusahaan pengiriman untuk mengirimkan pesanan Anda. Saat Anda membeli produk, kami akan membagikan nama, alamat, detail kartu kredit Anda, jumlah pembelian yang diperlukan oleh pihak ketiga untuk menyediakan layanan itu. Informasi kartu kredit ditransmisikan melalui koneksi terenkripsi SSL yang aman ke prosesor pembayaran kami dan disimpan dalam pusat data yang memenuhi PCI Level 1 sampai transaksi selesai, pada titik mana itu dihapus seluruhnya kecuali Anda telah meminta untuk menyimpan rincian kartu kredit Anda dengan aman di prosesor untuk transaksi di masa depan. Tidak ada informasi kartu kredit yang disimpan di server kami. Saat mengirimkan pesanan, informasi kontak Anda diteruskan ke mitra pengiriman kami untuk tujuan menghitung ongkos kirim, membeli label pengiriman, dan melacak pengiriman. Perusahaan-perusahaan ini tidak menyimpan, membagikan, menyimpan atau menggunakan informasi yang dapat diidentifikasi secara pribadi untuk tujuan lain apa pun. Pihak ketiga ini dilarang menggunakan informasi pribadi Anda untuk tujuan promosi. Semua pihak tersebut berkewajiban untuk mematuhi persyaratan privasi yang secara substansial mirip dengan Kebijakan Privasi ini, dan untuk memproses data sesuai dengan instruksi kami.</p>
        <p>" . env('APP_TITLE') . " tidak membagikan, menjual, menyewakan, atau memperdagangkan PII dengan pihak ketiga untuk tujuan promosi mereka. Kami dapat mengungkapkan atau mentransfer Informasi Pribadi (dan informasi terkait lainnya) jika perlu atau sesuai. untuk memproses pesanan; untuk melindungi keamanan Website; untuk melindungi diri kita sendiri dan perusahaan terafiliasi kita dari tanggung jawab; untuk melindungi pelanggan kami; untuk menanggapi panggilan dari pengadilan, proses pengadilan, atau permintaan yang sah oleh petugas penegak hukum; jika kita percaya dengan itikad baik bahwa hukum menuntutnya; kepada pembeli sehubungan dengan penjualan, penugasan, atau transfer lainnya dari semua atau sebagian dari bisnis atau perusahaan kami; atau di mana kami percaya dengan itikad baik bahwa demi kepentingan kesehatan, keselamatan atau perlindungan pihak ketiga mana pun. Dalam situasi apa pun ini, penerima Informasi Pribadi mungkin berlokasi di Amerika Serikat atau yurisdiksi lain yang mungkin tidak memberikan tingkat perlindungan data yang setara dengan undang-undang di yurisdiksi rumah Anda.</p>
        <p>Jika Anda menggunakan blog atau meninjau produk di Website ini, Anda harus mengetahui bahwa informasi pengenal pribadi yang Anda kirimkan di sana dapat dibaca, dikumpulkan, atau digunakan oleh pengguna lain di forum ini, dan dapat digunakan untuk mengirimi Anda pesan yang tidak diminta. Kami tidak bertanggung jawab atas informasi pengenal pribadi yang Anda pilih untuk dikirim di forum-forum ini.</p>
        <h4><b>Tautan ke Situs Lain</b></h4>
        <p>Website ini berisi tautan ke situs lain yang tidak dimiliki atau dikendalikan oleh " . env('APP_TITLE') . ". Perlu diketahui bahwa kami tidak bertanggung jawab atas praktik privasi dari situs lain tersebut. Kami mendorong Anda untuk waspada ketika Anda meninggalkan Website kami dan membaca pernyataan privasi masing-masing dan setiap situs yang mengumpulkan informasi yang dapat diidentifikasi secara pribadi. Pernyataan privasi ini hanya berlaku untuk informasi yang dikumpulkan oleh Website ini.</p>
        <h4><b>Akses ke Informasi Pribadi</b></h4>
        <p>Jika Anda ingin memperbarui Informasi Pribadi apapun yang sebelumnya Anda berikan, atau untuk menggunakan hak akses, perbaikan, penghapusan, atau penolakan apa pun terhadap pemrosesan Informasi Pribadi Anda yang mungkin Anda miliki berdasarkan hukum yang berlaku, silakan hubungi kami di " . env('MAIL_USERNAME') . ". Kami biasanya akan dengan senang hati memenuhi permintaan Anda sebagaimana mestinya, tetapi kami berhak untuk menggunakan Informasi Pribadi yang diperoleh sebelumnya untuk memverifikasi identitas Anda dan sebagaimana dijelaskan dalam Kebijakan Privasi ini. Untuk mengakses dan memperbarui Informasi Pribadi Anda, Anda juga dapat masuk ke akun " . env('APP_TITLE') . " Anda dan klik \"Pengaturan Akun.\"</p>
        <h4><b>Keamanan Data</b></h4>
        <p>Kami menerapkan berbagai tindakan pengamanan untuk menjaga keamanan informasi pribadi Anda ketika Anda melakukan pemesanan atau memasukkan, mengirim, atau mengakses informasi pribadi Anda.</p>
        <h4 data-toc-text=\"Perubahan Pernyataan\"><b>Perubahan Pernyataan dalam Kebijakan Privasi ini</b></h4>
        <p>Jika kami memutuskan untuk mengubah kebijakan privasi kami, kami akan memposting perubahan itu ke pernyataan privasi ini, halaman rumah, dan tempat-tempat lain yang kami anggap tepat sehingga Anda mengetahui informasi apa yang kami kumpulkan, bagaimana kami menggunakannya, dan dalam keadaan apa, jika ada, kami ungkapkan. Silakan periksa Kebijakan Privasi ini secara berkala dan khususnya sebelum Anda mengirimkan informasi tambahan melalui Website.</p>
        <p>Kami berhak mengubah Kebijakan Privasi ini dari waktu ke waktu dan atas kebijakan kami sendiri, kecuali jika pemberitahuan atau persetujuan sebelumnya diharuskan oleh hukum. Jika kami membuat perubahan materi pada kebijakan ini, kami akan memberi tahu Anda di sini, melalui email, atau dengan pemberitahuan di halaman Beranda kami.</p>
        <p>" . env('APP_TITLE') . " dapat menyediakan karya seni pihak ketiga untuk dimasukkan ke dalam produk " . env('APP_TITLE') . ". " . env('APP_TITLE') . " memiliki karya seni itu atau telah melisensikan hak untuk menggunakan karya seni itu untuk dimasukkan ke dalam produk-produk " . env('APP_TITLE') . ". Penggunaan karya seni di Website untuk tujuan lain dilarang. Dilarang mereproduksi karya seni dari produk " . env('APP_TITLE') . " atau dari Website.</p>"
];
