<?php
return [
    "head" => "Syarat dan Ketentuan",
    "capt" => "Syarat dan ketentuan penggunaan " . env('APP_TITLE') . ".",
    "content" =>
        "<p>Selamat datang di " . env('APP_TITLE') . " (di sini disebut sebagai \"Website\", \"" . env('APP_TITLE') . "\", \"Kami\", \"Kita\", \"Milik Kami\" dan afiliasinya). Halaman ini menjelaskan syarat-syarat dimana Anda dapat menggunakan website kami yang disediakan pada atau sehubungan dengan layanan (di sini disebut sebagai \"Layanan\"). Dengan mengakses atau menggunakan website " . env('APP_TITLE') . " (di sini disebut sebagai \"Website\", \"" . env('APP_TITLE') . "\", \"we\", \"us\", \"our\" dan afiliasinya), Anda menandakan bahwa Anda telah membaca, memahami, dan setuju untuk terikat oleh Syarat & Ketentuan ini (selanjutnya disebut \"Ketentuan\") dan untuk pengumpulan dan penggunaan informasi Anda sebagaimana diatur dalam Kebijakan Privasi " . env('APP_TITLE') . ". Ketentuan ini berlaku untuk semua pengunjung, pengguna dan orang lain yang mengakses Layanan. Jika Anda tidak setuju untuk terikat oleh semua Ketentuan ini, jangan mengakses atau menggunakan " . env('APP_TITLE') . ".</p>
        <h4><b>1. Penggunaan Website</b></h4>
        <p>Website ini diberikan kepada Anda untuk penggunaan Anda dengan tunduk pada Syarat dan Ketentuan ini. Dengan menggunakan Website Anda setuju untuk terikat oleh (i) Ketentuan ini dan (ii) Syarat dan Ketentuan Instagram ™ & Facebook ™. Meskipun kami biasanya hanya akan menolak penggunaan Website jika Syarat dan Ketentuan ini dilanggar, kami berhak menolak penggunaan Website kepada siapa pun dengan alasan apa pun kapan saja.</p>
        <h4 data-toc-text=\"2. Mendaftar\"><b>2. Mendaftar Akun " . env('APP_TITLE') . "</b></h4>
        <p>Untuk mendaftar/membuat akun (\"" . env('APP_TITLE') . "\") di Website, Anda harus berusia lebih dari tiga belas tahun. Anda harus memastikan bahwa perincian yang diberikan oleh Anda saat mendaftar atau kapan saja adalah benar dan lengkap. Anda harus segera memberi tahu kami setiap perubahan pada informasi yang Anda berikan saat pendaftaran dengan memperbarui perincian pribadi Anda agar kami dapat berkomunikasi dengan Anda secara efektif. Kami berhak menolak pendaftaran nama akun yang melanggar merek dagang atau dapat menyesatkan pengguna lain.</p>
        <h4><b>3. Kata Sandi dan Keamanan</b></h4>
        <p>Untuk mendaftar/membuat akun (\"" . env('APP_TITLE') . "\") di Website, Anda harus berusia lebih dari tiga belas tahun. Anda harus memastikan bahwa perincian yang diberikan oleh Anda saat mendaftar atau kapan saja adalah benar dan lengkap. Anda harus segera memberi tahu kami setiap perubahan pada informasi yang Anda berikan saat pendaftaran dengan memperbarui perincian pribadi Anda agar kami dapat berkomunikasi dengan Anda secara efektif. Kami berhak menolak pendaftaran nama akun yang melanggar merek dagang atau dapat menyesatkan pengguna lain.</p>
        <h4 data-toc-text=\"4. Larangan Penggunaan\"><b>4. Larangan Penggunaan Website</b></h4>
        <p>Anda tidak boleh menggunakan Website untuk tujuan berikut:</p>
        <ul><li>menyebarkan materi yang melanggar hukum, melecehkan, memfitnah, kasar, mengancam, berbahaya, vulgar, cabul, atau tidak menyenangkan atau melanggar hukum apapun;</li><li>mentransmisikan materi yang mendorong perilaku yang merupakan tindak pidana, atau melanggar hukum, peraturan, atau kode praktik apa pun yang berlaku;</li><li>mengganggu penggunaan orang lain atau kesenangan dari Situs; atau membuat, mentransmisikan atau menyimpan salinan materi elektronik yang dilindungi hak cipta tanpa izin dari pemiliknya.</li><li>Anda akan bertanggung jawab atas kerugian dan biaya kami sebagai akibat dari pelanggaran Anda atas ketentuan ini.</li></ul>
        <h4><b>5. Konten Anda di Website</b></h4>
        <p>Anda sepenuhnya bertanggung jawab atas konten (\"Konten\") yang Anda kirimkan, poskan, dan tampilkan di Website, dan segala kerusakan yang diakibatkan dari pengiriman, pengeposan, dan tampilan konten di Website. Ini termasuk, tanpa batasan, memposting materi ke Website, memposting tautan di Website, mengomentari Website atau membuat (atau mengizinkan pihak ketiga untuk membuat) materi tersedia melalui Website. Itu terjadi terlepas dari apakah Konten merupakan data, teks, file, informasi, gambar, nama layar, grafik, foto, profil, file audio, file video, kombinasi audiovisual, fitur interaktif, karya musik, karya kepengarangan, aplikasi, tautan, kode, skrip, perangkat lunak komputer, atau materi lainnya. Dengan menyediakan Konten, Anda menyatakan dan menjamin itu</p>
        <p>Hak kepemilikan, termasuk tetapi tidak terbatas pada hak cipta, paten, merek dagang, hak rahasia dagang, dan hak kekayaan intelektual lainnya dari pihak ketiga mana pun dalam Konten tidak akan dilanggar dengan menyalin, mengunduh, dan menggunakan Konten; Jika hak kekayaan intelektual atau hak kepemilikan dari Konten milik majikan Anda, Anda harus memiliki (i) menerima izin dari majikan Anda untuk memposting atau menyediakan Konten, termasuk tetapi tidak terbatas pada perangkat lunak apa pun, atau (ii) dijamin dari majikan Anda pengabaian tentang semua hak dalam atau untuk Konten. Setiap lisensi pihak ketiga yang berkaitan dengan Konten harus sepenuhnya dipenuhi dan berhasil melewati untuk pengguna akhir di bawah persyaratan yang diperlukan dan semua royalti, biaya dan uang lainnya karena orang dan yang terkait dengan penggunaan Konten harus telah sepenuhnya dan sepatutnya diselesaikan; Konten ini bebas dari bug, virus, worm, malware, trojan horse atau konten berbahaya atau merusak lainnya; Konten ini bukan spam, bukan mesin- atau yang dibuat secara acak, dan tidak mengandung konten komersial yang tidak etis atau tidak diinginkan yang dirancang untuk mengarahkan lalu lintas ke situs pihak ketiga atau meningkatkan peringkat mesin pencari dari situs pihak ketiga, atau untuk tindakan yang melanggar hukum lebih lanjut (seperti phish ing) atau menyesatkan penerima tentang sumber materi (seperti spoofing); Konten tidak mengandung materi pornografi, ancaman, atau materi yang memicu agresi terhadap individu atau entitas, dan tidak melanggar nama pengguna Akun " . env('APP_TITLE') . " Anda tidak akan menyesatkan pembaca Anda dengan berpikir bahwa Anda adalah orang atau perusahaan lain. Kami dapat, tetapi tidak memiliki kewajiban untuk, menghapus Konten dan Akun " . env('APP_TITLE') . " yang mengandung Konten yang, menurut kebijakan kami sendiri, adalah melanggar hukum, menyinggung, mengancam, memfitnah, memfitnah, cabul atau sebaliknya tidak pantas atau melanggar hak kekayaan intelektual atau hak kepemilikan lainnya dari orang lain, Perjanjian (khususnya, Syarat dan Ketentuan ini) dan Syarat dan Ketentuan Instagram ™ dan Facebook ™.</p>
        <p>Hak kami untuk menggunakan Konten Anda di Website. Kami TIDAK mengklaim hak kepemilikan APAPUN dalam Konten yang Anda kirimkan, poskan, dan tampilkan pada atau melalui Website. Dengan mengirimkan, memposting, dan menampilkan Konten apa pun di atau melalui Website, Anda dengan ini memberikan kepada kami lisensi non-eksklusif, dibayar penuh dan bebas royalti, di seluruh dunia, terbatas untuk menggunakan, memodifikasi, mengadaptasi, menghapus dari, menambah, melakukan, untuk secara publik , memperlihatkan kepada publik, mereproduksi, mentransmisikan, menyimpan, menerjemahkan, menerbitkan, menyiarkan, mendistribusikan, atau mengeksploitasi Konten tersebut, termasuk tanpa batasan, adaptasi, reproduksi, dan distribusi sebagian atau seluruh Konten dalam format media apa pun melalui saluran media apa pun melalui saluran media apapun.</p>
        <h4 data-toc-text=\"6. Aktivitas Pengunjung\"><b>6. Aktivitas Pengunjung di Website</b></h4>
        <p>Kami belum mengevaluasi, dan tidak dapat mengevaluasi, semua Konten yang diposting oleh pengunjung (yaitu orang yang menilai Website dan tanpa Akun " . env('APP_TITLE') . ") ke Website (\"Konten Pengunjung\"), dan tidak akan bertanggung jawab atas Konten Pengunjung. atau penggunaan atau efeknya. Dengan menggunakan Website, kami tidak mendukung atau menyiratkan bahwa kami mendukung Konten Pengunjung, atau bahwa kami percaya Konten Pengunjung tersebut akurat, bermanfaat atau tanpa membahayakan. Anda bertanggung jawab untuk mengambil tindakan pencegahan yang diperlukan untuk membela diri dan sistem komputer Anda dari bug, virus, worm, trojan horse, dan konten berbahaya atau merusak lainnya. Website ini dapat memuat Konten Pengunjung yang menyinggung, tidak senonoh, atau tidak menyenangkan, serta mengandung ketidakakuratan teknis, kesalahan ketik, dan kesalahan lainnya. Website ini juga dapat memuat Konten Pengunjung yang melanggar privasi atau hak publisitas, atau melanggar kekayaan intelektual dan hak kepemilikan lainnya, dari pihak ketiga, atau mengunduh, menyalin, atau menggunakan yang tunduk pada syarat dan ketentuan tambahan, tersurat atau tersirat. Kami menafikan setiap dan semua tanggung jawab atas segala kerugian yang diakibatkan oleh penggunaan oleh pengunjung Website, penyerahan, pengeposan, dan tampilan Konten Pengunjung di Website atau dari pengunduhan oleh pengunjung dari setiap Konten di Website.</p>
        <h4 data-toc-text=\"7. Pembayaran / Pesanan Anda\"><b>7. Pembayaran / Pesanan Anda di Website</b></h4>
        <p>Pesanan yang ditempatkan di Website dikenakan biaya impor, pajak, bea masuk, biaya penanganan paket terkait dan/atau biaya terkait lainnya yang diperlukan oleh negara yang ditunjuk dan/atau organisasi yang menangani pengiriman / pengiriman pesanan. Tidak satu pun dari biaya ini yang termasuk dalam harga yang Anda bayar di Website. Barang tidak dapat dikirim sebagai hadiah, dan pembelian Anda mungkin atau mungkin tidak memiliki biaya ini, tergantung pada kebijakan negara yang ditunjuk dan/atau organisasi yang menangani paket. Jika salah satu dari biaya tersebut berlaku, Anda mungkin harus membayarnya ke otoritas penagihan masing-masing sebelum menerima pembelian Anda. Anda harus memeriksa dengan otoritas terkait negara Anda (atau negara yang ditunjuk pesanan) untuk setiap biaya yang diperlukan untuk menerima barang yang Anda pesan dari " . env('APP_TITLE') . ". " . env('APP_TITLE') . " tidak bertanggung jawab atas semua biaya ini, dan tidak akan mengembalikan barang yang dikembalikan kepada kami karena alasan yang tidak dapat diterima / tidak terkirim dan/atau alasan lainnya kecuali jika disetujui sebaliknya dengan " . env('APP_TITLE') . " sebelumnya. Selain itu, karena produk dari " . env('APP_TITLE') . " sangat disesuaikan dan dibuat khusus untuk masing-masing pelanggan dan dibuat khusus untuk pelanggan individu, produk tidak dapat dikembalikan untuk pengembalian dana. Jika Anda tidak puas dengan cacat pada produk (seperti kasing atau percetakan), silakan hubungi tim layanan pelanggan kami untuk bantuan dan tim akan menyelidiki masalah dan mengatur pertukaran produk dengan yang baru jika perlu.</p>
        <h4><b>8. Ketersediaan Website</b></h4>
        <p>Meskipun kami bertujuan untuk menawarkan layanan terbaik kepada Anda, kami tidak berjanji bahwa layanan di Website akan memenuhi persyaratan Anda. Kami tidak dapat menjamin bahwa layanan ini bebas dari kesalahan. Jika terjadi kesalahan dengan Website Anda harus melaporkannya " . env('MAIL_USERNAME') . " dan kami akan berusaha untuk memperbaiki kesalahan secepat mungkin. Akses Anda ke Website mungkin sesekali dibatasi untuk memungkinkan perbaikan, pemeliharaan atau pengenalan fasilitas atau layanan baru. Kami akan berusaha memulihkan layanan secepat mungkin.</p>
        <h4><b>9. Website Pihak Ketiga</b></h4>
        <p>Website ini menyertakan tautan ke Website dan halaman web lain (\"Website Pihak Ketiga\"). Kami belum meninjau, dan tidak dapat meninjau, semua materi yang tersedia melalui Website Pihak Ketiga yang ditautkan oleh Website dan tautan ke Website tersebut. Kami tidak memiliki kendali atas Website Pihak Ketiga, dan tidak akan bertanggung jawab atas konten, penggunaan, kebijakan privasi, atau praktiknya. Dengan menautkan ke Website Pihak Ketiga, kami tidak menyatakan atau menyiratkan bahwa kami mendukung Website Pihak Ketiga tersebut. Anda bertanggung jawab untuk mengambil tindakan pencegahan yang diperlukan untuk melindungi diri Anda dan sistem komputer Anda dari virus, worm, trojan horse, dan konten berbahaya atau merusak lainnya. Kami menafikan setiap dan semua tanggung jawab atas segala kerugian yang diakibatkan dari penggunaan Anda atas Website Pihak Ketiga.</p>
        <h4><b>10. Properti Intelektual</b></h4>
        <p>Konten yang kami tampilkan di Website (\"Konten " . env('APP_TITLE') . "\") dilindungi oleh hak cipta, merek dagang, paten, rahasia dagang, database dan hak kekayaan intelektual lainnya, yang dimiliki atau dilisensikan kepada kami. Kami dengan ini memberi Anda lisensi terbatas, dapat ditarik kembali, tidak dapat disublisensikan untuk mereproduksi dan menampilkan Konten " . env('APP_TITLE') . " (tidak termasuk kode perangkat lunak apa pun) semata-mata untuk melihat dan menggunakan Website. Anda tidak boleh menyalin, mereproduksi, menyediakan secara online atau mentransmisikan, menerbitkan, mengadaptasi, mendistribusikan, mentransmisikan, menyiarkan, menampilkan, menjual, melisensikan, atau mengeksploitasi Konten " . env('APP_TITLE') . " apa pun tanpa izin tertulis dari kami atau pemilik hak kekayaan intelektual. . Perjanjian tidak mengalihkan kepada Anda hak kekayaan intelektual kami atau pihak ketiga mana pun, dan semua hak, hak milik, dan kepentingan di dalam dan atas properti tersebut akan tetap (seperti di antara para pihak) semata-mata bersama kami. Lebih lanjut, logo " . env('APP_TITLE') . ", dan semua merek dagang, merek layanan, grafik, dan logo lain yang digunakan bersama dengan " . env('APP_TITLE') . " atau di Website adalah merek dagang atau merek dagang terdaftar atau hak kekayaan intelektual lain dari Perusahaan atau pemberi lisensi kami. Merek dagang, tanda layanan, grafik, dan logo lain yang digunakan dalam kaitannya dengan Website mungkin adalah merek dagang atau hak kekayaan intelektual lainnya dari pihak ketiga lainnya. Penggunaan Website ini tidak memberi Anda hak atau lisensi untuk mereproduksi atau menggunakan merek dagang, tanda layanan, gambar, dan logo pihak ketiga atau kami.</p>
        <h4><b>11. Pelanggaran Hak Cipta</b></h4>
        <p>Saat kami meminta orang lain untuk menghormati hak kekayaan intelektual kami, kami menghormati hak kekayaan intelektual orang lain. Jika Anda yakin bahwa materi yang terletak di atau ditautkan ke atau dari Website ini melanggar hak cipta Anda, Anda disarankan untuk memberi tahu kami. Kami akan menggunakan upaya wajar kami untuk menanggapi semua pemberitahuan tersebut, dan jika diperlukan atau sesuai, menghapus materi yang melanggar atau menonaktifkan semua tautan ke materi yang melanggar. Kami dapat, tetapi tidak berkewajiban untuk mengakhiri izin pengunjung untuk mengunjungi dan menggunakan Website jika, dalam kondisi yang tepat, pengunjung bertekad untuk menjadi pelanggar berulang atas hak cipta atau hak kekayaan intelektual lainnya dari Perusahaan atau orang lain.</p>
        <h4><b>12. Penafian Warna</b></h4>
        <p>Karena perbedaan di antara monitor warna, warna pada monitor komputer Anda mungkin tampak berbeda dari produk yang sebenarnya. Selain itu, ada varian alami di semua media tergantung pada kerapatan dan keropos bahan, tekstur, finishing, dll yang dapat menyebabkan variasi warna untuk setiap produk.</p>
        <h4><b>13. Perubahan Pernyataan</b></h4>
        <p>Kami berhak untuk mengubah Perjanjian (khususnya, Syarat dan Ketentuan ini) dari waktu ke waktu karena alasan hukum atau peraturan atau untuk memungkinkan operasi yang tepat dari Website. Setiap perubahan materi dalam Perjanjian (khususnya, Syarat dan Ketentuan ini) akan diberitahukan kepada Anda melalui alamat email yang Anda berikan saat registrasi atau dipublikasikan melalui pengumuman yang sesuai di Website. Meskipun demikian, Anda harus secara berkala meninjau versi terbaru dari Ketentuan ini. Perubahan akan berlaku untuk penggunaan Website segera setelah pemberitahuan tersebut diberikan. Apa yang merupakan perubahan material akan ditentukan atas kebijakan kami sendiri. Jika Anda tidak ingin menerima Perjanjian baru ini, Anda tidak boleh terus menggunakan Website. Jika Anda terus menggunakan Website setelah mengajukan perubahan pada Website, penggunaan Website tersebut merupakan persetujuan Anda untuk terikat oleh Perjanjian baru (khususnya, Syarat dan Ketentuan baru). Kami juga dapat, di masa depan, menawarkan layanan dan/atau fitur baru melalui Website (termasuk, pelepasan alat dan sumber daya baru). Fitur dan/atau layanan baru tersebut harus tunduk pada Perjanjian (khususnya, Syarat dan Ketentuan).</p>
        <h4><b>14. Penangguhan Akun</b></h4>
        <p>Kami berhak untuk menangguhkan atau membatalkan Akun " . env('APP_TITLE') . " Anda kapan saja, tanpa pemberitahuan sebelumnya dan atas kebijakan kami sendiri jika Anda melanggar kewajiban Anda berdasarkan Syarat dan Ketentuan ini. Jika Anda ingin mengakhiri Akun " . env('APP_TITLE') . " Anda, Anda dapat memberi tahu kami secara tertulis di [email]. Penangguhan atau pembatalan Akun Castegram Anda tidak akan memengaruhi hak kami dan kewajiban Anda yang timbul sebelum penangguhan / pembatalan tersebut. Semua ketentuan Perjanjian (khususnya, Syarat dan Ketentuan), yang menurut sifatnya harus selamat dari pengakhiran, akan tetap berlaku setelah pengakhiran Perjanjian, termasuk, tanpa batasan, kekayaan intelektual, representasi dan jaminan, ganti rugi, penafian jaminan, dan batasan tanggung jawab.</p>
        <h4><b>15. Error Website</b></h4>
        <p>Dalam hal suatu produk terdaftar di Website dengan harga yang salah atau dengan informasi yang salah, pesanan untuk produk tersebut akan direvisi untuk mencerminkan harga atau informasi yang benar. Kami berhak menolak pesanan apa pun yang ditempatkan di situs.</p>
        <h4><b>16. Indemnifikasi</b></h4>
        <p>Anda setuju untuk mengganti rugi dan tidak membahayakan, sejauh yang diizinkan oleh undang-undang yang berlaku, Perusahaan, kontraktor kami, pemberi lisensi dan pemegang lisensi, dan masing-masing direktur, pejabat, anggota, karyawan dan agen kami dari dan terhadap setiap dan semua klaim, tuntutan, perselisihan, tindakan, proses, penyebab tindakan, penilaian, kerusakan, kerugian, kewajiban, biaya atau pengeluaran (termasuk tanpa batasan, biaya dan pengeluaran pengacara, dan semua biaya dan pengeluaran yang terjadi dalam pemulihan jumlah yang disebutkan di atas), timbul di luar penggunaan Anda atas Website, termasuk tetapi tidak terbatas pada pelanggaran Anda terhadap Perjanjian (khususnya, Syarat dan Ketentuan) dan Syarat dan Ketentuan Instagram ™ & Facebook ™.</p>
        <h4><b>17. Penafian Jaminan</b></h4>
        <p>Website disediakan \"sebagaimana adanya\". Kami, pemasok, pemberi lisensi, dan pemegang lisensi kami dengan ini menafikan semua jaminan dalam bentuk apa pun, tersurat maupun tersirat, termasuk, tanpa batasan, jaminan dapat diperjualbelikan, kesesuaian untuk tujuan tertentu, dan tidak melanggar hak kekayaan intelektual, hak kepemilikan atau undang-undang lainnya. Persyaratan. Baik kami maupun pemasok, pemberi lisensi, atau pemegang lisensi kami tidak membuat jaminan apa pun bahwa Website akan bebas dari kesalahan atau bahwa akses ke sana akan berkelanjutan atau tidak terputus. Anda akan mengunduh dari, atau mendapatkan konten atau layanan melalui, Website dengan kebijaksanaan dan risiko Anda sendiri.</p>
        <h4><b>18. Kewajiban " . env('APP_TITLE') . "</b></h4>
        <p>Anda memahami bahwa ketika menggunakan Website, Anda akan terpapar ke konten dari situs internet atau sumber di luar Website, dan bahwa kami tidak bertanggung jawab atas keakuratan, kegunaan, keamanan, atau hak kekayaan intelektual atau terkait dengan konten tersebut. Anda selanjutnya memahami dan mengakui bahwa Anda mungkin terpapar pada konten yang tidak akurat, menyinggung, tidak senonoh, atau tidak menyenangkan, dan Anda setuju untuk mengesampingkan hak atau pemulihan hukum atau keadilan yang Anda miliki atau mungkin miliki terhadap kami sehubungan dengan hal tersebut di atas, dan, untuk sejauh diizinkan oleh hukum yang berlaku, setuju untuk mengganti rugi dan membebaskan Perusahaan, kontraktor, pemberi lisensi dan pemegang lisensi, dan direktur, pejabat, anggota, karyawan, dan agen kami masing-masing sejauh yang diizinkan oleh hukum mengenai semua hal yang berkaitan untuk penggunaan Anda atas Website. Lebih lanjut, jika kami melanggar Syarat dan Ketentuan ini, kami hanya akan bertanggung jawab atas kerugian yang Anda derita sebagai akibat sejauh konsekuensi tersebut dapat diperkirakan baik untuk kami dan Anda pada saat Anda menggunakan Website. Tanggung jawab kami dalam hal apa pun tidak termasuk kerugian bisnis seperti kehilangan data, kehilangan laba, atau gangguan bisnis, tetapi tidak akan membatasi atau memengaruhi tanggung jawab kami yang dihasilkan dari produk apa pun yang dijual melalui Website yang ditemukan tidak aman atau jika sesuatu yang kami lakukan dengan kelalaian menyebabkan kematian atau cedera pribadi.</p>
        <h4><b>19. Batasan Kewajiban</b></h4>
        <p>Sejauh diizinkan oleh hukum yang berlaku, Perusahaan, kontraktor, pemberi lisensi, dan pemegang lisensi kami, dan direktur, pejabat, anggota, karyawan, dan agen kami masing-masing tidak bertanggung jawab berkenaan dengan masalah apa pun dalam Perjanjian ini ( khususnya, Syarat dan Ketentuan) berdasarkan kontrak, kelalaian, kewajiban ketat atau teori hukum atau keadilan lainnya untuk (i) setiap kerugian atau pengeluaran khusus, insidental, hukuman atau kerusakan konsekuensial; (ii) biaya pengadaan atau penggantian produk atau layanan; (iii) untuk gangguan penggunaan atau kehilangan atau kerusakan data; atau (iv) untuk jumlah yang melebihi biaya yang dibayarkan kepada Anda oleh Anda selama periode dua belas (12) bulan sebelum akrual penyebab tindakan. Kami tidak bertanggung jawab atas kegagalan atau keterlambatan karena hal-hal di luar kendali kami yang wajar.</p>
        <h4><b>20. Pengiklanan dan Sokongan</b></h4>
        <p>Bagian dari Website dapat berisi materi iklan dan sponsor. Pengiklan dan sponsor bertanggung jawab untuk memastikan bahwa materi yang dikirimkan untuk dimasukkan di Website mematuhi hukum yang relevan. Kami tidak akan bertanggung jawab kepada Anda atas kesalahan atau ketidakakuratan dalam iklan atau materi sponsor yang diposting di Website.</p>
        <h4><b>21. Penggunaan Internasional</b></h4>
        <p>Kami tidak berjanji bahwa materi di Website ini sesuai atau tersedia untuk digunakan di lokasi di luar Indonesia. Akses ke Website dari lokasi di mana isinya secara hukum ilegal atau melanggar hukum dilarang. Jika Anda memilih untuk mengakses Website dari lokasi di luar Indonesia, Anda melakukannya atas inisiatif Anda sendiri dan Anda akan sepenuhnya bertanggung jawab untuk mematuhi hukum setempat.</p>
        <h4><b>22. Tidak Ada Kemitraan</b></h4>
        <p>Kami dan Anda akan dan bertindak secara independen dan bukan sebagai mitra, venturer bersama, agen, karyawan, atau atasan lainnya. Anda tidak akan memiliki wewenang untuk mengambil atau membuat kewajiban apa pun untuk atau atas nama Perusahaan, tersurat maupun tersirat, dan Anda tidak akan berusaha mengikat kami pada kontrak apa pun.</p>
        <h4 data-toc-text=\"23. Representasi & Jaminan\"><b>23. Representasi Umum dan Jaminan</b></h4>
        <p>Anda menyatakan dan menjamin bahwa penggunaan Website Anda akan sesuai ketat dengan kebijakan privasi kami, Perjanjian (khususnya, Syarat dan Ketentuan ini) dan semua hukum dan peraturan yang berlaku (termasuk tanpa batasan hukum atau peraturan setempat di negara Anda, negara bagian, kota, atau area pemerintahan lainnya, berkenaan dengan perilaku online dan konten yang dapat diterima, dan termasuk.</p>
        <h4><b>24. Lain-Lain</b></h4>
        <p>Perjanjian, termasuk Syarat dan Ketentuan ini, akan merupakan seluruh perjanjian antara kami dan Anda mengenai pokok permasalahan dalam Perjanjian ini, dan hanya dapat dimodifikasi oleh amandemen tertulis yang ditandatangani oleh eksekutif resmi Perusahaan, atau dengan posting di Website versi revisi. Kecuali sejauh hukum yang berlaku, jika ada, memberikan sebaliknya, Perjanjian, akses ke atau penggunaan Website akan diatur oleh hukum Indonesia, dan para pihak sepakat untuk tunduk pada yurisdiksi non-eksklusif pengadilan Indonesia. . Jika ada bagian dari Perjanjian ini dianggap tidak sah atau tidak dapat dilaksanakan, itu akan dipotong dan bagian yang tersisa akan tetap berlaku penuh dan efek. Pengabaian oleh salah satu pihak dari Syarat atau Ketentuan ini atau pelanggaran apa pun daripadanya, dalam satu contoh, tidak akan mengesampingkan syarat atau ketentuan tersebut atau pelanggaran berikutnya. Anda dapat menetapkan hak-hak Anda berdasarkan Perjanjian kepada pihak mana pun yang menyetujui, dan setuju untuk terikat oleh Perjanjian. Kami dapat menetapkan hak kami berdasarkan Perjanjian tanpa syarat. Perjanjian akan mengikat dan akan berlaku untuk kepentingan para pihak, penerus mereka dan penugasan yang diizinkan.</p>"
];
