<?php
return [
    "head" => "Terms and Conditions",
    "capt" => "Terms and conditions of the " . env('APP_TITLE') . " usage.",
    "content" =>
        "<p>Welcome to " . env('APP_TITLE') . " (herein referred to as \"Website\", \"" . env('APP_TITLE') . "\", \"We\", \"Us\", \"Our\" and their affiliates). This page explains the terms by which you may use our website provided on or in connection with the service (herein referred to as \"Service\"). By accessing or using the " . env('APP_TITLE') . " website (herein referred to as \"Website\", \"" . env('APP_TITLE') . "\", \"we\", \"us\", \"our\" and their affiliates), you signify that you have read, understood, and agree to be bound by these Terms &amp; condition (herein referred to as \"Terms\") and to the collection and use of your information as set forth in the " . env('APP_TITLE') . " Privacy Policy. These Terms applies to all visitors, users and others who access the Service. If you do not agree to be bound by all these Terms, do not access or use " . env('APP_TITLE') . ".</p>
        <h4><b>1. Use of the Website</b></h4>
        <p>The Website is provided to you for your use subject to these Terms and Conditions. By using the Website you agree to be bound by (i) these Terms and (ii) the Instagram™ &amp; Facebook™ Terms and Conditions. Although we will normally only refuse use of the Website if these Terms and Conditions are violated, we reserve the right to refuse use of the Website to anyone for any reason at any time.</p>
        <h4 data-toc-text=\"2. Signing Up\"><b>2. Signing up a " . env('APP_TITLE') . " Account</b></h4>
        <p>To register an account (\"" . env('APP_TITLE') . " Account\") on the Website, you must be over thirteen years of age. You must ensure that the details provided by you on registration or at any time are correct and complete. You must inform us immediately of any changes to the information that you provided on registration by updating your personal details in order that we can communicate with you effectively. We reserve the right to refuse registration of any account name that violates a trademark or may mislead other users.</p>
        <h4><b>3. Password and Security</b></h4>
        <p>To register an account (\"" . env('APP_TITLE') . " Account\") on the Website, you must be over thirteen years of age. You must ensure that the details provided by you on registration or at any time are correct and complete. You must inform us immediately of any changes to the information that you provided on registration by updating your personal details in order that we can communicate with you effectively. We reserve the right to refuse registration of any account name that violates a trademark or may mislead other users.</p>
        <h4 data-toc-text=\"4. Usage Restrictions\"><b>4. Website Usage Restrictions</b></h4>
        <p>You may not use the Website for any of the following purposes:</p>
        <ul><li>disseminating any unlawful, harassing, libellous, abusive, threatening, harmful, vulgar, obscene, or otherwise objectionable material or otherwise breaching any laws;</li><li>transmitting material that encourages conduct that constitutes a criminal offence, or otherwise breaches any applicable laws, regulations or code of practices;</li><li>interfering with any other person's use or enjoyment of the Website; or making, transmitting or storing electronic copies of materials protected by copyright without permission of the owner.</li><li>You will be responsible for our losses and costs resulting from your breach of this provision.</li></ul>
        <h4><b>5. Your Content on the Website</b></h4>
        <p>You are entirely responsible for the content (the \"Content\") that you submit, post and display on the Website, and any harm resulting from the submission, posting and display of the contents on the Website. These include, without limitation, posting material to the Website, posting links on the Website, commenting on the Website or otherwise making (or allowing any third party to make) material available via the Website. That is the case regardless of whether the Content constitutes data, text, files, information, images, screen names, graphics, photos, profiles, audio files, video files, audiovisual combinations, interactive features, musical works, works of authorship, applications, links, codes, scripts, computer software or other material. By making the Content available, you represent and warrant that.</p>
        <p>The proprietary rights, including but not limited to the copyright, patent, trademark, trade secret rights and other intellectual property rights of any third party in the Content will not be infringed by the copying, downloading and use of the Content; If the intellectual property rights or proprietary rights of the Contents belong to your employer, you must have either (i) received permission from your employer to post or make available the Content, including but not limited to any software, or (ii) secured from your employer a waiver as to all rights in or to the Content.Any third-party licenses relating to the Content must be fully complied with and successfully pass through to end users under any required terms and all royalties, fees and other monies owing to other persons and relating to the use of the Content must have been fully and duly settled;The Content is free from any bugs, viruses, worms, malware, trojan horses or other harmful or destructive content;The Content is not spam, is not machine- or randomly-generated, and does not contain unethical or unwanted commercial content designed to drive traffic to third party sites or boost the search engine rankings of third party sites, or to further unlawful acts (such as phishing) or mislead recipients as to the source of the material (such as spoofing);The Content does not contain any pornographic material, threats or material which incites aggression towards individuals or entities, and does not infringeYour " . env('APP_TITLE') . " Account username will not mislead your readers into thinking that you are another person or company.We may, but has no obligation to, remove the Content and the " . env('APP_TITLE') . " Account(s) containing Content that, in our sole discretion, are unlawful, offensive, threatening, libelous, defamatory, obscene or otherwise objectionable or violates the intellectual property rights or other proprietary rights of others, the Agreement (in particular, these Terms and Conditions) and the Instagram™ and Facebook™ Terms and Conditions.</p>
        <p>Our right to use Your Content on Website. We do NOT claim ANY ownership rights in the Content that you submit, post and display on or via the Website. By submitting, posting and displaying any Content on or via the Website, you hereby grant to us a non-exclusive, fully paid and royalty-free, worldwide, limited license to use, modify, adapt, delete from, add to, publicly perform, publicly display, reproduce, transmit, store, translate, publish, broadcast, distribute, sell or otherwise exploit such Content, including without limitation, the adaptation, reproduction and distribution of part or all of the Content in any media formats through any media channels.</p>
        <h4 data-toc-text=\"6. Visitors' Activities\"><b>6. Visitors' Activities on the Website</b></h4>
        <p>We have not evaluated, and cannot evaluate, all of the Contents posted by visitors (i.e. persons assessing the Website and without a " . env('APP_TITLE') . " Account) to the Website (\"Visitors' Contents\"), and will not be responsible for the Visitors\' Contents or their use or effects. By using the Website, we do not stand for or imply that we supports the Visitors' Contents, or that we believe such Visitors' Contents to be accurate, useful or without harm. You are responsible for taking precautions as necessary to defend yourself and your computer systems from bugs, viruses, worms, trojan horses, and other harmful or destructive content. The Website may contain Visitors\' Contents that are offensive, indecent, or otherwise objectionable, as well as containing technical inaccuracies, typographical mistakes, and other errors. The Website may also contain Visitors\' Contents that violate the privacy or publicity rights, or breach the intellectual property and other proprietary rights, of third parties, or the downloading, copying or use of which are subject to additional terms and conditions, express or implied. We disclaim any and all responsibility for any harm resulting from the use by visitors of the Website, the submission, posting and display of Visitors\' Content on the Website or from any downloading by those visitors of any Content on the Website.</p>
        <h4 data-toc-text=\"7. Your Payment / Orders\"><b>7. Your Payment / Orders on the Website</b></h4>
        <p>The orders placed on the Website are subjecting to being charged with import fees, taxes, custom duties, related package handling fees and/or any other relevant charges required by the corresponding designated country and/or the organization(s) that handle(s) the shipment / delivery of the orders. None of these charges are included in the price that you pay on the Website. Items cannot be sent as gifts, and your purchase may or may not have these charges, depending on the policies of the designated country and/or the organization(s) that handle(s) the package. If any of the said charges apply, you may need to pay for them to the respective collection authority in advance of receiving your purchase. You should check with any related authority of your country (or the designated country of the order) for any charges required to receive the goods you order from " . env('APP_TITLE') . " . " . env('APP_TITLE') . " is not responsible for any of these charges, and would not refund on item(s) returned to us due to unaccepted / undelivered and/or any other reasons unless otherwise agreed with " . env('APP_TITLE') . " in advance. Furthermore, since products from " . env('APP_TITLE') . " are highly customized and tailor-made for individual customized and tailor-made for individual customers, products cannot be returned for refund. If you are not satisfied by defects on the products (such as scratched cases or printing), please contact our customer services team for assistance and the team will investigate the problem and arrange an exchange of the product with a new one if necessary.</p>
        <h4><b>8. Availability of the Website</b></h4>
        <p>Although we aim to offer you the best service possible, we make no promise that the services at the Website will meet your requirements. We cannot guarantee that the services will be fault-free. If a fault occurs with the Website you should report it {{env('MAIL_USERNAME')}} and we will attempt to correct the fault as soon as it reasonably can. Your access to the Website may be occasionally restricted to allow for repairs, maintenance or the introduction of new facilities or services. We will attempt to restore the service as soon as we reasonably can.</p>
        <h4><b>9. Third Party Websites</b></h4>
        <p>The Website includes links to other websites and webpages (\"Third Party Websites\"). We have not reviewed, and cannot review, all of the material made available through the Third Party Websites to which the Website links and that link to the Website. We do not have any control over the Third Party Websites, and will not be responsible for their contents, use, privacy policies, or practices. By linking to a Third Party Website, we do not represent or imply that we endorse such Third Party Website. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, trojan horses, and other harmful or destructive content. We disclaim any and all responsibility for any harm resulting from your use of the Third Party Websites.</p>
        <h4><b>10. Intellectual Property</b></h4>
        <p>The content we display on the Website (the \"" . env('APP_TITLE') . " Content\") is protected by copyright, trademark, patent, trade secret, database and other intellectual property rights, which is either owned by or licensed to us. We hereby grant you a limited, revocable, non-sublicensable license to reproduce and display the " . env('APP_TITLE') . " Content (excluding any software code) solely for viewing and using the Website. You may not copy, reproduce, make available online or transmit, publish, adapt, distribute, transmit, broadcast, display, sell, license, or otherwise exploit any of the " . env('APP_TITLE') . " Content without written permission from us or the owner of the intellectual property rights. The Agreement does not transfer to you any of our or the third party\'s intellectual property rights, and all rights, titles and interests in and to such property will remain (as between the parties) solely with us. Further, the " . env('APP_TITLE') . " logo, and all other trademarks, service marks, graphics and logos used in association with " . env('APP_TITLE') . " or on the Website are the trademarks or registered trademarks or other intellectual property rights of the Company or our licensors. Other trademarks, service marks, graphics and logos used in association with the Website may be the trademarks or other intellectual property rights of other third parties. Your use of the Website grants you no right or license to reproduce or otherwise use any of our or third party\'s trademarks, service marks, graphics and logos.</p>
        <h4><b>11. Copyright Infringement</b></h4>
        <p>As we ask others to respect our intellectual property rights, we respect the intellectual property rights of others. If you believe that material located on or linked to or from the Website violates your copyright, you are encouraged to notify us. We will use our reasonable endeavours to respond to all such notices, and if required or appropriate, remove the infringing material or disable all links to the infringing material. We may, but has no obligation to end a visitor’s permission to visit and use the Website if, under appropriate conditions, the visitor is determined to be a repeat infringer of the copyrights or other intellectual property rights of the Company or others.</p>
        <h4><b>12. Colour Disclaimer</b></h4>
        <p>Due to variances among colour monitors, the colours on your computer monitor may appear differently than the actual product. Moreover, there are natural variances in all media depending on the material density and porousness, textures, finishing, etc that may cause colour variations for each product.</p>
        <h4><b>13. Statement Changes</b></h4>
        <p>We reserve the right to amend the Agreement (in particular, these Terms and Conditions) from time to time for legal or regulatory reasons or to allow the proper operation of the Website. Any material changes in the Agreement (in particular, these Terms and Conditions) will be notified to you via the email address provided by you on registration or published via a suitable announcement on the Website. You should nonetheless periodically review the up-to-date version of these Terms. The changes will apply to the use of the Website immediately after such notice has been given. What constitutes a material change will be determined at our sole discretion. If you do not wish to accept any of the new Agreement, you must not continue to use the Website. If you continue to use the Website after the positing of the amendments on the Website, your use of the Website constitutes your agreement to be bound by the new Agreement (in particular, the new Terms and Conditions). We may also, in the future, offer new services and/or features through the Website (including, the release of new tools and resources). Such new features and/or services shall be subject to the Agreement (in particular, the Terms and Conditions).</p>
        <h4><b>14. Account Termination</b></h4>
        <p>We reserve the right to suspend or cancel your " . env('APP_TITLE') . " Account at any time, without prior notice and in our sole discretion if you breach any of your obligations under these Terms and Conditions. If you wish to terminate your " . env('APP_TITLE') . " Account, you may inform us in writing at [email]. Suspension or cancellation of your Castegram Account shall not affect our and your rights and liabilities accrued before such suspension/cancellation. All provisions of the Agreement (in particular, the Terms and Conditions), which by their nature should survive termination, shall survive termination of the Agreement, including, without limitation, intellectual property, representations and warranties, indemnification, disclaimer of warranties, and limitations of liability.</p>
        <h4><b>15. Site Errors</b></h4>
        <p>In the event a product is listed on the Website at an incorrect price or with incorrect information, orders for such products will be revised to reflect the correct price or information. We reserve the right to reject any orders placed on the site.</p>
        <h4><b>16. Indemnification</b></h4>
        <p>You agree to indemnify and hold harmless, to the fullest extent permitted under the applicable law, the Company, our contractors, licensors and licensees, and our/their respective directors, officers, members, employees and agents from and against any and all claims, demands, disputes, actions, proceedings, causes of action, judgments, damagers, losses, liabilities, costs or expenses (including without limitation, attorneys’ fees and expenses, and all costs and expenses incurred in the recovery of the aforesaid amounts), arising out of your use of the Website, including but not limited to your violation of the Agreement (in particular, the Terms and Conditions) and the Instagram™ &amp; Facebook™ Terms and Conditions.</p>
        <h4><b>17. Disclaimer of Warranties</b></h4>
        <p>The Website is provided “as is”. We, our suppliers, licensors and licensees hereby disclaim all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement of any intellectual property rights, other proprietary rights or statutory requirements. Neither we nor our suppliers, licensors or licensees make any warranty that the Website will be error free or that access thereto will be continuous or uninterrupted. You will download from, or otherwise obtain content or services through, the Website at your own discretion and risk.</p>
        <h4><b>18. " . env('APP_TITLE') . "'s liability</b></h4>
        <p>You understand that when using the Website, you will be exposed to content from internet sites or sources outside the Website, and that we are not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such content. You further understand and acknowledge that you may be exposed to content that is inaccurate, offensive, indecent or objectionable, and you agree to waive any legal or equitable rights or remedies you have or may have against us with respect to the aforesaid, and, to the fullest extent permitted under the applicable law, agree to indemnify and hold harmless the Company, our contractors, licensors and licensees, and our/their respective directors, officers, members, employees and agents to the fullest extent allowed by law regarding all matters relating to your use of the Website. Further, if we are in breach of these Terms and Conditions, we will only be responsible for any loss that you suffer as a result to the extent they are a foreseeable consequence to both we and you at the time you use the Website. Our liability shall not in any event include business losses such as lost data, lost profits or business interruption, but shall not limit or affect our liability resulting from any products sold through the Website being found to be unsafe or if something we do negligently causes death or personal injury.</p>
        <h4><b>19. Limitation of Liability</b></h4>
        <p>To the fullest extent permitted under the applicable law, in no event will the Company, our contractors, licensors and licensees, and our/their respective directors, officers, members, employees and agents be liable with respect to any subject matter of the Agreement (in particular, the Terms and Conditions) under any contract, negligence, strict liability or other legal or equitable theory for (i) any special, incidental, punitive losses or expenses or consequential damages; (ii) the cost of procurement or substitute products or services; (iii) for interruption of use or loss or corruption of data; or (iv) for any amounts that exceed the fees paid to us by you during the twelve (12) month period prior to the accrual of the cause of action. We shall have no liability for any failure or delay due to matters beyond our reasonable control.</p>
        <h4><b>20. Advertising and Sponsorship</b></h4>
        <p>Part of the Website may contain advertising and sponsorship material. Advertisers and sponsors are responsible for ensuring that material submitted for inclusion on the Website complies with the relevant law. We will not be responsible to you for any error or inaccuracy in advertising or sponsorship material posted on the Website.</p>
        <h4><b>21. International Use</b></h4>
        <p>We make no promise that material on the Website is appropriate or available for use in locations outside Indonesia. Access to the Website from locations where its contents are by law illegal or unlawful is prohibited. If you choose to access the Website from locations outside Indonesia, you do so on your own initiative and you will be entirely responsible for compliance with local laws.</p>
        <h4><b>22. No partnership</b></h4>
        <p>We and you shall be and act independently and not as partner, joint venturer, agent, employee or employer of the other. You shall not have any authority to assume or create any obligation for or on behalf of the Company, express or implied, and you shall not attempt to bind us to any contract.</p>
        <h4 data-toc-text=\"23. Representation & Warranty\"><b>23. General Representation and Warranty</b></h4>
        <p>You represent and warrant that your use of the Website will be in strict accordance with our privacy policy, the Agreement (in particular, these Terms and Conditions) and all applicable laws and regulations (including without limitation any local laws or regulations in your country, state, city, or other governmental area, regarding online conduct and acceptable content, and including.</p>
        <h4><b>24. Miscellaneous</b></h4>
        <p>The Agreement, including these Terms and Conditions, shall constitute the entire agreement between we and you concerning the subject matter hereof, and may only be modified by a written amendment signed by an authorized executive of the Company, or by the posting on the Website of a revised version. Except to the extent the applicable law, if any, provides otherwise, the Agreement, any access to or use of the Website will be governed by the laws of Indonesia, and the parties agree to submit to the non-exclusive jurisdiction of the Indonesia courts. If any part of the Agreement is held invalid or unenforceable, it will be severed and the remaining portions will remain in full force and effect. A waiver by either party of any of these Terms or Conditions or any breach thereof, in any one instance, will not waive such term or condition or any subsequent breach thereof. You may assign your rights under the Agreement to any party that consents to, and agrees to be bound by the Agreement. We may assign our rights under the Agreement without condition. The Agreement will be binding upon and will inure to the benefit of the parties, their successors and permitted assigns.</p>"
];
